### ISSUE TITLE
how to run the project without GPU?

### ISSUE THREAD

**Issue by saghafi** [3ZadeSSG/TwitterSentimentAnalysisApp#2]
is it possible to run the notebook which is in the second folder "Training with preprocessed data"
without GPU and Cuda? if it is possible which changes can I make?

**Comment by 3ZadeSSG** [comment]
Hi, the notebook can be ran without GPU but it will be very slow during training. That's why I didn't write any flags to toggle between CPU & GPU Training. Anyways, you will have to do some modifications in the code, just search with ".cuda" and comment the lines which are converting the variables from CPU to GPU for example `inputs,labels=inputs.cuda().long(),labels.cuda().long()`
But do not touch the SentimentNetwork class.

I looked there are 6 lines which needs to be disabled by comments.

**Comment by saghafi** [comment]
thanks for your recommendation it resolved my issue
